extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-maven
  container: maven
pipelines:
  pullRequest:
    build:
      steps:
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""

  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only --tag
        name: tag-with-new-version
    build:
      steps:
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat VERSION)
        name: changelog
        image: gcr.io/jenkinsxio/builder-go


