extends:
  import: classic
  file: go/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - name: make-test
        command: make test
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""
  release:
    build:
      replace: true
      steps:
      - name: make-build
        command: make release
        image: gcr.io/jenkinsxio-labs/go-releaser:0.0.18
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        image: gcr.io/jenkinsxio-labs-private/jxl
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION) --no-apply
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: update-version
      - sh: "echo disabled: jx gitops helm template --optional"
        name: helm-template
        image: gcr.io/jenkinsxio/jx-cli
        comment: lets release the versioned kubernetes resources for consumption via kubectl/kpt/kustomize
      - sh: jx step tag --version \$(cat VERSION)
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: tag-version

