extends:
  import: classic
  file: javascript/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
          image: gcr.io/jenkinsxio/builder-go
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview
          image: gcr.io/jenkinsxio-labs-private/jx-cli

  release:
    build:
      steps:
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --batch-mode --version v\$(cat ../../VERSION)
          name: changelog
          image: gcr.io/jenkinsxio-labs-private/jxl
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
          image: gcr.io/jenkinsxio-labs-private/jxl
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h
          name: jx-promote
          image: gcr.io/jenkinsxio-labs-private/jx-cli
    setVersion:
      steps:
      - sh: jx step next-version --filename package.json
        name: next-version
        image: gcr.io/jenkinsxio-labs-private/jxl
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION) --no-apply
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: update-version
      - sh: "echo disabled: jx gitops helm template --optional"
        name: helm-template
        image: gcr.io/jenkinsxio-labs-private/jx-cli
        comment: lets release the versioned kubernetes resources for consumption via kubectl/kpt/kustomize
      - sh: jx step tag --version \$(cat VERSION)
        image: gcr.io/jenkinsxio-labs-private/jxl
        name: tag-version
