agent:
  label: jenkins-machine-learning-gpu
  container: machine-learning-gpu
pipelines:
  pullRequest:
    build:
      steps:
      - sh: source /root/.bashrc && git lfs install && git lfs pull
      - sh: source /root/.bashrc && flake8
        name: flake8
      - sh: source /root/.bashrc && pytest
        name: testing
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
          name: make-preview
          image: gcr.io/jenkinsxio/builder-go
        - sh: jx preview --app $APP_NAME --dir ../..
          name: jx-preview
          image: gcr.io/jenkinsxio/jx-cli
  release:
    setup:
      steps:
      - groovy: git 'https://REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.git'
        when: "prow"
      - sh: git lfs install && git lfs pull
      - sh: git checkout master
        comment: ensure we're not on a detached head
        when: "!prow"
      - sh: git config --global credential.helper store
        when: "!prow"
      - sh: jx step git credentials
        when: "!prow"
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION)
    build:
      steps:
      - sh: source /root/.bashrc && flake8
        name: flake8
      - sh: source /root/.bashrc && pytest
        name: testing
      - sh: /kaniko/executor $KANIKO_FLAGS --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
        env:
        - name: NO_GOOGLE_APPLICATION_CREDENTIALS
          value: "true"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: ""
    promote:
      steps:
      - dir: ./charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          name: changelog
          image: gcr.io/jenkinsxio/builder-go
        - comment: release the helm chart
          sh: jx step helm release
          name: helm-release
          image: gcr.io/jenkinsxio/builder-go
        - comment: promote through all 'Auto' promotion Environments
          sh: jx promote -b --all-auto --timeout 1h
          image: gcr.io/jenkinsxio/jx-cli
  post:
    steps:
    - groovy: always
      when: "!prow"
      steps:
      - groovy: "cleanWs()"
