extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: gcr.io/jenkinsxio-labs/jxl
pipelines:
  release:
    pipeline:
      stages:
      - name: release
        agent:
          image: gcr.io/jenkinsxio-labs/jxl
        options:
          volumes:
          - name: jx-boot-secrets
            secret:
              secretName: jx-boot-secrets
          containerOptions:
            env:
            - name: HELM_PLUGINS
              value: "/root/.cache/helm/plugins"
            - name: XDG_CONFIG_HOME
              value: "/builder/home"
            - name: JX_SECRETS_YAML
              value: "/secrets/jx-boot/secrets.yaml"
            volumeMounts:
            - mountPath: /secrets/jx-boot
              name: jx-boot-secrets
        steps:
        - args:
          - step
          - git
          - validate
          command: jx
          dir: /workspace/source
          name: validate-git
        - args:
          - step
          - verify
          - preinstall
          - --disable-verify-packages
          - --provider-values-dir="kubeProviders"
          command: jx
          dir: /workspace/source
          name: verify-preinstall
        - args:
          - upgrade
          - crd
          command: jx
          name: install-jx-crds
        - args:
          - step
          - create
          - helmfile
          command: jx
          dir: /workspace/source
          name: generate-helmfile
        - command: ./kubectl-apply.sh
          dir: /workspace/source
          name: kubectl-apply
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/system
          name: helmfile-system
        - args:
          - step
          - verify
          - ingress
          - --ingress-namespace=nginx
          - --ingress-service=nginx-ingress-controller
          command: jx
          dir: /workspace/source
          name: verify-ingress
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/apps
          name: helmfile-apps
        - args:
          - step
          - git
          - credentials
          - -o
          - /builder/home/git/credentials
          command: jx
          dir: /workspace/source
          name: git-creds
        - args:
          - step
          - verify
          - env
          command: jx
          dir: /workspace/source
          name: verify-jenkins-x-environment
        - args:
          - step
          - scheduler
          - config
          - apply
          - --direct=true
          command: jx
          dir: /workspace/source
          name: install-pipelines
        - args:
          - update
          - webhooks
          - --verbose
          - --warn-on-fail
          command: jx
          dir: /workspace/source
          name: update-webhooks
        - args:
          - step
          - verify
          - install
          - --pod-wait-time
          - 30m
          command: jx
          dir: /workspace/source
          name: verify-installation

  pullRequest:
    pipeline:
      stages:
      - name: pr-checks
        agent:
          image: gcr.io/jenkinsxio-labs/jxl
        options:
          volumes:
          - name: jx-boot-secrets
            secret:
              secretName: jx-boot-secrets
          containerOptions:
            env:
            - name: HELM_PLUGINS
              value: "/root/.cache/helm/plugins"
            - name: JX_SECRETS_YAML
              value: "/secrets/jx-boot/secrets.yaml"
            volumeMounts:
            - mountPath: /secrets/jx-boot
              name: jx-boot-secrets
        steps:
        - args:
          - step
          - create
          - helmfile
          command: jx
          dir: /workspace/source
          name: create-helmfile
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/system
          name: lint-helmfile-system
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/apps
          name: lint-helmfile-apps



