extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: gcr.io/jenkinsxio-labs-private/jxl
pipelines:
  release:
    pipeline:
      stages:
      - name: release
        agent:
          image: gcr.io/jenkinsxio-labs-private/jxl
        options:
          volumes:
          - name: jx-boot-secrets
            emptyDir: {}
          containerOptions:
            env:
            - name: HELM_PLUGINS
              value: "/root/.cache/helm/plugins"
            - name: XDG_CONFIG_HOME
              value: "/builder/home"
            - name: JX_SECRETS_YAML
              value: "/secrets/jx-boot/secrets.yaml"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - mountPath: /secrets/jx-boot
              name: jx-boot-secrets
        steps:
        - args:
          - boot
          - secrets
          - export
          - --dir=.
          command: jxl
          dir: /workspace/source
          name: verify-secrets
        - args:
          - step
          - git
          - validate
          command: jx
          dir: /workspace/source
          name: validate-git
        - args:
          - step
          - verify
          - preinstall
          - --disable-verify-packages
          command: jx
          dir: /workspace/source
          name: verify-preinstall
        - args:
          - step
          - create
          - helmfile
          command: jx
          dir: /workspace/source
          name: generate-helmfile
        - args:
          - diff
          command: helmfile
          dir: /workspace/source/system
          name: helmfile-system-diff
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/system
          name: helmfile-system
        - args:
          - step
          - verify
          - ingress
          command: jx
          dir: /workspace/source
          name: verify-ingress
          image: gcr.io/jenkinsxio-labs-private/jxl
        - args:
          - kubectl annotate sourcerepositories --all meta.helm.sh/release-name=repositories;
            kubectl annotate sourcerepositories --all meta.helm.sh/release-namespace=$NAMESPACE;
            kubectl label sourcerepositories --all app.kubernetes.io/managed-by=Helm;
          command: ["/bin/sh", "-c"]
          dir: /workspace/source
          name: helm-annotate-source-repositories
          image: gcr.io/jenkinsxio-labs-private/jxl
        - args:
          - diff
          command: helmfile
          dir: /workspace/source/apps
          name: helmfile-apps-diff
        - args:
          - sync
          command: helmfile
          dir: /workspace/source/apps
          name: helmfile-apps
        - args:
          - step
          - git
          - credentials
          - -o
          - /builder/home/git/credentials
          command: jx
          dir: /workspace/source
          name: git-creds
        - args:
          - step
          - verify
          - env
          command: jx
          dir: /workspace/source
          name: verify-jenkins-x-environment
        - args:
          - step
          - scheduler
          - config
          - apply
          - --direct=true
          command: jx
          dir: /workspace/source
          name: install-pipelines
        - args:
          - step
          - verify
          - dns
          - --timeout
          - 10m
          command: jx
          dir: /workspace/source
          name: verify-dns
        - args:
          - update
          - webhooks
          - --verbose
          - --warn-on-fail
          command: jx
          dir: /workspace/source
          name: update-webhooks
        - args:
          - step
          - verify
          - install
          - --pod-wait-time
          - 30m
          command: jx
          dir: /workspace/source
          name: verify-installation

  pullRequest:
    pipeline:
      stages:
      - name: pr-checks
        agent:
          image: gcr.io/jenkinsxio-labs-private/jxl
        options:
          volumes:
          - name: jx-boot-secrets
            emptyDir: {}
          containerOptions:
            env:
            - name: HELM_PLUGINS
              value: "/root/.cache/helm/plugins"
            - name: JX_SECRETS_YAML
              value: "/secrets/jx-boot/secrets.yaml"
            volumeMounts:
            - mountPath: /secrets/jx-boot
              name: jx-boot-secrets
        steps:
        - args:
          - boot
          - secrets
          - export
          - --dir=.
          command: jxl
          dir: /workspace/source
          name: verify-secrets
        - args:
          - step
          - create
          - helmfile
          command: jx
          dir: /workspace/source
          name: create-helmfile
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/system
          name: lint-helmfile-system
        - args:
          - lint
          command: helmfile
          dir: /workspace/source/apps
          name: lint-helmfile-apps



